### ISSUE TITLE
ek rupee ki pepsi dipyanshu baby sexy 

### ISSUE THREAD

**Issue by krakos-afk** [DipanshuAmbilkar03/Computer-graphics-LAB-EXPERIMENT-SPPU-2019#6]

**Comment by krakos-afk** [comment]
WTF is this chatgpt ahhaassss code

**Comment by DipanshuAmbilkar03** [comment]
> WTF is this chatgpt ahhaassss code
>ek rupee ki pepsi dipyanshu baby sexy 
complaining or complementing ?
